- src/GeometryTypes.jl
- src/types.jl
Hey Simon,
As per our discussion at https://github.com/rohitvarkey/Compose3D.jl/issues/2, I was trying to make the primitives I'm using GeometryType primitives. For this, I would like to have an abstract type, say "GeometryPrimitive", as a super type for all the primitives. This will help me make sure that I'll be creating geometries in Compose3D only for these types rather than all FixedSizeArrays. 
I was able to convert the sphere primitive I was using earlier to the GeometryType.Sphere type you have after these changes to GeometryTypes. The working code is at https://github.com/rohitvarkey/Compose3D.jl/tree/geometryTypes. 
I'm guessing this will help others also with similar intentions to identify geometry primitives also!
Regards,
Rohit.
> Abstract Types for Primitives

- .travis.yml
- src/GeometryTypes.jl
- src/meshtypes.jl
I removed FileIO so the only contingent package is FSA. There were also some artifacts in Travis so that it was only testing the `ntuples` branch.
cc @SimonDanisch
> WIP: Get closer to tagging

- src/GeometryTypes.jl
- src/decompose.jl
- src/deprecated.jl
- src/faces.jl
- test/hyperrectangles.jl
- test/meshtypes.jl
Implementing Face{3} and Face{2} for #20 to see how the syntax works out. The big issue is that the `NTuple{Face}` is not valid, so `Tuple` must be used instead. I think finding a general word for this would be good.
> Face{N} -> Face{2} via Tuple{Face{2}}(f) for #20

- src/deprecated.jl
- src/types.jl
This is so we can subtype HyperRectangle in forthcoming releases (startign with v0.2.0). Part of the on-going project to unify types.
> deprecate Rectangle and rename as SimpleRectangle

- src/slice.jl
I was getting a `BoundsError` without this.
> Fix slice to use the correct offset

- src/GeometryTypes.jl
- src/checkbounds.jl
- src/faces.jl
- test/faces.jl
- test/meshtypes.jl
- test/runtests.jl
#28 brought this method to my attention so I made some tweaks for codegen.
Apologies for my aversion to regular macro style. I really can't figure out hygiene and have gotten perhaps too good at avoiding it.
Open questions:
- Should we make unsafe_getindex the default?
I have tested some packages depending on this and they don't seem to care that the return type changed to tuple. (we will need to tag v0.2.0 after this though). 
CC: @SimonDanisch @dreammaker 
**Before**
```
julia> @code_native getindex([1,2,3,4],f)
.text
Filename: /home/steve/.julia/v0.4/GeometryTypes/src/faces.jl
Source line: 2
pushq	%rbp
movq	%rsp, %rbp
Source line: 2
pushq	%r15
pushq	%r14
pushq	%r12
pushq	%rbx
subq	$48, %rsp
movq	$8, -80(%rbp)
movabsq	$jl_pgcstack, %r14
movq	(%r14), %rax
movq	%rax, -72(%rbp)
leaq …
```
> Improve codegen for getindex(::Array, ::Face)

- src/convexhulls.jl
- src/gjk.jl
- test/convexhulls.jl
- test/gjk.jl
Fixed issues from wrong calculation of vertices of HyperCubes, HyperRectangles like:
Wrong:
```
using Geometry Types
HyperCube(Vec(0,0), 1) |> vertices
(Vec(-0.5,-0.5),Vec(-0.5,0.5),Vec(0.5,-0.5),Vec(0.5,0.5))
```
Correct:
```
using Geometry Types
HyperCube(Vec(0,0), 1) |> vertices
(Vec(0,0),Vec(0,1),Vec(1,0),Vec(1,1))
```
> fixed rects

- src/faces.jl
- src/typealias.jl
- src/types.jl
- test/REQUIRE
closes #89 
supersedes #95 
@SimonDanisch I have surrendered to your wisdom regarding the construction of OffsetIntegers from plain Integers. This just flips the offset signs back to match the old GeometryTypes behavior (and the documentation) and cleans up the convert() methods a bit, so they should work for integer types other than just (Int64, Int32, UInt64, UInt32).
> change Offset polarity to match old behavior, and clean up conversion

- REQUIRE
- src/GeometryTypes.jl
- src/gjk.jl
- src/hyperrectangles.jl
- src/lines.jl
- src/meshes.jl
- src/simplices.jl
- src/typealias.jl
- src/types.jl
- src/typeutils.jl
Sorry for the crazy number of PRs today. I've been busy 😉 and wanted to keep the various changes as small and discrete as possible. 
This removes all the compatibility clutter and fully upgrades to v0.6 syntax. It should prevent deprecation warnings on the v0.7 nightlies ~~(but the nightly tests will fail until #95 #97  comes in first).~~
> fully upgrade to v0.6 syntax and remove Compat.jl

- src/meshes.jl
- test/meshes.jl
fixes #90 
The fallback method for `convert()` for meshes assumed that `AbstractMesh <: AbstractGeometry` which is no longer the case.
> Fix mesh conversion

- src/meshes.jl
- test/meshes.jl
The current HomogenousMesh constructor is doing a lot of reflection on its input types at runtime, and somehow that's triggering the segfault in #92. Switching it to a generated function actually seems like an improvement anyway, since it moves most of that work to compile-time, and it also fixes the segfault (for some reason). 
fixes #92
> convert HomogenousMesh constructor to an @generated function to work around segfault

- REQUIRE
`Normed` requires FixedPointNumbers v0.3 as pointed out by @tkelman
> Require Normed v0.3

- src/faces.jl
- src/types.jl
- test/faces.jl
This fixes the errors on win32 in https://github.com/JuliaIO/MeshIO.jl/pull/31
The problem is that the following works:
```julia
julia> UInt64(1) - 1
0x0000000000000000
```
but adding `-1` fails, because Julia tries to promote both arguments to `UInt64`:
```julia
julia> UInt64(1) + -1
ERROR: InexactError()
```
So we just have to add or subtract appropriately depending on the sign of the offset.
> fix InexactErrors due to promotion to unsigned integer types

- src/meshes.jl
Simple fix, updates deprecated syntax and addresses both issue #118 and the corresponding issue in GLVisualize.jl.
> Correct deprecated syntax for map! in meshes.jl. Resolves issue #118.

- .travis.yml
- README.md
- REQUIRE
- appveyor.yml
- docs/build/types.md
- src/GeometryTypes.jl
- src/decompose.jl
- src/distancefields.jl
- src/hyperrectangles.jl
- src/lines.jl
- src/meshes.jl
- src/typealias.jl
- src/types.jl
- test/lines.jl
- test/runtests.jl
- test/simplerectangle.jl
The only outright failures on v0.7 were where we were abusing `sub2ind((v,), j, i)` by passing it a 1-dimensional first argument and then indexing with two dimensions. I replaced those calls with `(i - 1) * v + j`. 
The remaining deprecations are all due to constructors no longer falling back to convert methods. I'm still trying to figure out the right way to handle that: https://discourse.julialang.org/t/recommended-style-for-conversion-vs-constructors-in-v0-7/11561
> Fix tests and most deprecations on v0.7-alpha

- .travis.yml
- REQUIRE
- appveyor.yml
- src/faces.jl
Fixes a few more deprecation warnings on Julia v0.7. I also raised the minimum Julia version to v0.7-alpha to avoid accidentally breaking 0.6.
> create constructors instead of convert methods for OffsetInteger

- src/FixedSizeArrays.jl
- src/GeometryTypes.jl
- src/types.jl
This patch allows the JuliaArrays/StaticArrays.jl repository to deprecate StaticArrays.FixedSizeArrays without affecting GeometricTypes.jl.
Resolves #132.
I am very new to Julia and I am not sure if this patch makes any sense. I am looking forward to receiving constructive feedback 🙂
> Vendorize StaticArrays.FixedSizeArrays

- src/FixedSizeArrays.jl
- test/baseutils.jl
Based on #174, makes `minimum(...)` behave consistently with `extrema(...)[1]` and `maximum(...)` with `extrema(...)[2]` (i.e. return the corner of the bounding box).
> Fixed inconsistency between extrema and minimum/maximum

- src/decompose.jl
- test/hyperrectangles.jl
Currently, the faces obtained by `decompose(Face, HyperRectangle{3})` are oriented towards the positive coordinate axes (assuming counter-clockwise winding order).
Since they enclose a volume, it would however make more sense if they pointed outwards (which would help with e.g. #144 or rendering with backface-culling enabled).
This PR thus fixes the orientation of the faces and adds a test to document this.
> Fix cuboid face orientation

- src/faces.jl
- src/types.jl
- test/faces.jl
Address https://github.com/JuliaGeometry/GeometryTypes.jl/issues/186
> Fix and test behavior of offset integers

- Project.toml
Can we have a new release? Merging https://github.com/JuliaGeometry/GeometryTypes.jl/pull/200 does not help unless you also make a new release.
> Set version to 0.8.2.
